In [2]:
import pickle
with open('../../results/benchmark_scan_multi/SOBOL_results_1.pkl', 'rb') as f: # X is 1,2,3 for different objectives 
    results_1, res_close, res_far = pickle.load(f) 
    print("optimal solution from optimization algorithm", results_1)
    print("stats for samples close to the optimal solution",  res_close)
    print(" stats for samples far away the optimal solution  ",  res_far)

optimal solution from optimization algorithm {'I_1': np.float64(0.01), 'I_3': np.float64(1.455395184538098), 'I_10': np.float64(0.9809055902412358)}
stats for samples close to the optimal solution [{'current': (np.float64(0.010657163585165278), np.float64(1.446264657817975), np.float64(0.9777752015916467)), 'parameters': (np.float64(5.498249348143299e-07), array([[ 0.00871946, -0.00512699,  0.00255144]]), array([[ 1.52470032e-04, -9.18025089e-05,  4.93639749e-05],
       [-9.18025089e-05,  5.28116127e-05, -2.89452524e-05],
       [ 4.93639749e-05, -2.89452524e-05,  1.31417446e-05]]), array([ 2.22719197e-04, -2.63537325e-06, -1.66043495e-06]), array([[-0.82924624,  0.41018469,  0.379604  ],
       [ 0.49292122,  0.21666897,  0.84266436],
       [-0.26339961, -0.88589112,  0.38186067]]))}, {'current': (np.float64(0.012697442774042441), np.float64(1.4590879508268104), np.float64(0.975869127275478)), 'parameters': (np.float64(6.661946125947646e-07), array([[ 0.00875681, -0.00513032,  0.002

In [10]:
print("="*50)
print("eigenvalues for samples close to the optimal solution")
for j in range(len(res_close)):
    print(res_close[j]["parameters"][-2]) # eigenvalues

print("="*50)
print("eigenvalues for samples far away the optimal solution")
for j in range(len(res_far)):
    print(res_far[j]["parameters"][-2]) # eigenvalues


eigenvalues for samples close to the optimal solution
[ 2.22719197e-04 -2.63537325e-06 -1.66043495e-06]
[ 2.24888963e-04 -2.92918835e-06 -1.82759517e-06]
[ 2.21758972e-04 -2.54598810e-06 -1.59569510e-06]
[ 2.24508631e-04 -2.77558245e-06 -1.74711824e-06]
[ 2.23864125e-04 -2.95506513e-06 -1.83015011e-06]
[ 2.21486474e-04 -2.58639285e-06 -1.61950830e-06]
[ 2.22736965e-04 -2.86981923e-06 -1.77710197e-06]
[ 2.23850364e-04 -2.85762762e-06 -1.78272322e-06]
[ 2.22735962e-04 -2.50492587e-06 -1.58283397e-06]
[ 2.22753569e-04 -2.72548898e-06 -1.70506609e-06]
eigenvalues for samples far away the optimal solution
[ 3.15098117e-04 -9.26910324e-05  2.95679368e-05]
[ 2.76180973e-04  2.55302193e-05 -3.78237407e-05]
[ 2.97575912e-04  1.33172844e-05 -1.44298813e-06]
[ 3.43656519e-04 -1.29301486e-04  4.24954614e-05]
[1.17570871e-04 1.66114920e-06 3.87624607e-06]
[ 1.15074574e-04 -6.10292400e-05  1.52854258e-05]
[ 2.35820837e-04  2.96782249e-05 -2.86092087e-05]
[ 1.67215219e-04  2.19595378e-05 -2.02420172e